name = "siyonsiyoni"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "pnpm run deploy"
publish = ".vercel/output/static"

[build.upload]
format = "directory"
dir = ".vercel/output/static"
